In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    'Student_ID': [101, 102, 103, 104, 105],
    'Name': ['Amit', 'Neha', 'Rahul', 'Sneha', 'Karan'],
    'Marks': [78, 0, 65, None, 88],
    'Attendance': [85, 90, 0, 75, 80],
    'Age': [20, 21, 20, 22, 21]
}

df = pd.DataFrame(data)

In [3]:
df.to_csv('students.csv', index=False)
df.to_excel('students.xlsx', index=False)

In [4]:
csv_df = pd.read_csv('students.csv')
excel_df = pd.read_excel('students.xlsx')

print(csv_df)

   Student_ID   Name  Marks  Attendance  Age
0         101   Amit   78.0          85   20
1         102   Neha    0.0          90   21
2         103  Rahul   65.0           0   20
3         104  Sneha    NaN          75   22
4         105  Karan   88.0          80   21

In [5]:
csv_df.shape

(5, 5)

In [6]:
csv_df.isnull().sum()

Student_ID    0
Name          0
Marks         1
Attendance    0
Age           0
dtype: int64

In [7]:
csv_df.dtypes

Student_ID      int64
Name           object
Marks         float64
Attendance      int64
Age             int64
dtype: object

In [8]:
(csv_df == 0).sum()

Student_ID    0
Name          0
Marks         1
Attendance    1
Age           0
dtype: int64

In [9]:
csv_df[['Name', 'Marks']]
csv_df.iloc[0:3]

   Student_ID   Name  Marks  Attendance  Age
0         101   Amit   78.0          85   20
1         102   Neha    0.0          90   21
2         103  Rahul   65.0           0   20

In [10]:
csv_df.sort_values(by='Marks', ascending=False)

   Student_ID   Name  Marks  Attendance  Age
4         105  Karan   88.0          80   21
0         101   Amit   78.0          85   20
2         103  Rahul   65.0           0   20
1         102   Neha    0.0          90   21
3         104  Sneha    NaN          75   22

In [11]:
csv_df.describe()

       Student_ID      Marks  Attendance       Age
count    5.000000   4.000000    5.000000   5.00000
mean   103.000000  57.750000   66.000000  20.80000
std      1.581139  39.634791   37.316216   0.83666
min    101.000000   0.000000    0.000000  20.00000
25%    102.000000  48.750000   75.000000  20.00000
50%    103.000000  71.500000   80.000000  21.00000
75%    104.000000  80.500000   85.000000  21.00000
max    105.000000  88.000000   90.000000  22.00000

In [12]:
csv_df.nunique()

Student_ID    5
Name          5
Marks         4
Attendance    5
Age           3
dtype: int64

In [13]:
csv_df.dtypes

Student_ID      int64
Name           object
Marks         float64
Attendance      int64
Age             int64
dtype: object

In [14]:
csv_df['Age'] = csv_df['Age'].astype(float)

csv_df['Student_ID'] = csv_df['Student_ID'].astype(str)

csv_df.dtypes

Student_ID     object
Name           object
Marks         float64
Attendance      int64
Age           float64
dtype: object